# Generated by Django 3.0.5 on 2020-04-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200418_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(to='core.Tweet'),
        ),
    ]
