# Generated by Django 3.0.5 on 2020-04-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(null=True, to='core.Tweet'),
        ),
    ]
