# Generated by Django 3.0.5 on 2020-04-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200418_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(null=True, to='core.Tweet'),
        ),
    ]
